import { Trip, Participant, Booking, Expense, Payment, LedgerEvent, Vendor, RefundEvent } from './types';

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'v1',
    tripId: 'trip-goa-2026',
    name: 'Taj Host Villas Goa',
    category: 'lodging',
    contactPhone: '+91 98230 11223',
    email: 'reservations@tajvillasgoa.com',
    website: 'https://tajvillasgoa.com',
    rating: 4.8,
    totalBookingsCount: 1,
    totalSpent: 68000,
  },
  {
    id: 'v2',
    tripId: 'trip-goa-2026',
    name: 'Goa Wheels Self-Drive',
    category: 'transport',
    contactPhone: '+91 98112 44556',
    email: 'rentals@goawheels.in',
    website: 'https://goawheels.in',
    rating: 4.6,
    totalBookingsCount: 1,
    totalSpent: 21500,
  },
  {
    id: 'v3',
    tripId: 'trip-goa-2026',
    name: 'Mandovi Luxury Marine',
    category: 'activity',
    contactPhone: '+91 97654 32100',
    email: 'charters@mandovimarine.in',
    website: 'https://mandovimarine.in',
    rating: 4.9,
    totalBookingsCount: 1,
    totalSpent: 30000,
  },
  {
    id: 'v4',
    tripId: 'trip-goa-2026',
    name: 'Thalassa Beach Restaurant',
    category: 'food',
    contactPhone: '+91 98221 88776',
    email: 'bookings@thalassagoa.com',
    rating: 4.7,
    totalBookingsCount: 1,
    totalSpent: 19800,
  },
  {
    id: 'v5',
    tripId: 'trip-goa-2026',
    name: 'Western Ghats Treks',
    category: 'activity',
    contactPhone: '+91 94481 99001',
    email: 'info@westernghatstreks.com',
    rating: 4.5,
    totalBookingsCount: 1,
    totalSpent: 8500,
  },
];

export const INITIAL_REFUNDS: RefundEvent[] = [];

export const INITIAL_TRIP: Trip = {
  id: 'trip-goa-2026',
  title: 'Goa & Gokarna Sunsets 2026',
  destination: 'Goa & Gokarna, India',
  baseCurrency: 'INR',
  startDate: '2026-08-28',
  endDate: '2026-09-04',
  budgetCeiling: 250000,
  inviteCode: 'GOA2026',
  organizerId: 'p1',
  createdAt: '2026-08-20T09:00:00Z',
};

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'p1',
    tripId: 'trip-goa-2026',
    name: 'Srushti Sharma',
    email: 'srushti@tripsync.in',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isOrganizer: true,
    status: 'active',
    upiId: 'srushti.sharma@okicici',
    weight: 1,
    roomTier: 'suite',
  },
  {
    id: 'p2',
    tripId: 'trip-goa-2026',
    name: 'Ananya Iyer',
    email: 'ananya@tripsync.in',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'ananya.iyer@upi',
    weight: 1,
    roomTier: 'standard',
  },
  {
    id: 'p3',
    tripId: 'trip-goa-2026',
    name: 'Rohan Mehta',
    email: 'rohan@tripsync.in',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'rohan.m@okhdfcbank',
    weight: 1,
    roomTier: 'standard',
  },
  {
    id: 'p4',
    tripId: 'trip-goa-2026',
    name: 'Priya Patel',
    email: 'priya@tripsync.in',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'priyapatel@paytm',
    weight: 1,
    roomTier: 'economy',
  },
  {
    id: 'p5',
    tripId: 'trip-goa-2026',
    name: 'Diya Verma',
    email: 'diya@tripsync.in',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'diya.v@ybl',
    weight: 1,
    roomTier: 'standard',
  },
  {
    id: 'p6',
    tripId: 'trip-goa-2026',
    name: 'Kabir Roy',
    email: 'kabir@tripsync.in',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'kabir.roy@postbank',
    weight: 1,
    roomTier: 'suite',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    tripId: 'trip-goa-2026',
    category: 'lodging',
    title: 'Heritage Beach Villa & Private Pool (Vagator)',
    vendor: 'Taj Host Villas Goa',
    startTime: '2026-08-28T15:00:00Z',
    endTime: '2026-09-02T11:00:00Z',
    estimatedCost: 65000,
    actualCost: 68000,
    status: 'confirmed',
    participantIds: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
  },
  {
    id: 'b2',
    tripId: 'trip-goa-2026',
    category: 'transport',
    title: 'Self-Drive 7-Seater SUV Rentals & Airport Pickup',
    vendor: 'Goa Wheels Self-Drive',
    startTime: '2026-08-28T12:00:00Z',
    endTime: '2026-09-04T16:00:00Z',
    estimatedCost: 22000,
    actualCost: 21500,
    status: 'confirmed',
    participantIds: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
  },
  {
    id: 'b3',
    tripId: 'trip-goa-2026',
    category: 'activity',
    title: 'Private Sunset Catamaran Yacht Charter & Scuba',
    vendor: 'Mandovi Luxury Marine',
    startTime: '2026-08-30T15:30:00Z',
    endTime: '2026-08-30T19:30:00Z',
    estimatedCost: 28000,
    actualCost: 30000,
    status: 'confirmed',
    participantIds: ['p1', 'p2', 'p3', 'p6'],
  },
  {
    id: 'b4',
    tripId: 'trip-goa-2026',
    category: 'activity',
    title: 'Gokarna Coastal Cliff Trek & Heritage Guide',
    vendor: 'Western Ghats Treks',
    startTime: '2026-09-03T08:00:00Z',
    endTime: '2026-09-03T17:00:00Z',
    estimatedCost: 9000,
    actualCost: 8500,
    status: 'confirmed',
    participantIds: ['p2', 'p3', 'p4', 'p5'],
  },
  {
    id: 'b5',
    tripId: 'trip-goa-2026',
    category: 'food',
    title: 'Thalassa Sunset Seafood Feast & Cocktails',
    vendor: 'Thalassa Beach Restaurant',
    startTime: '2026-08-31T20:00:00Z',
    endTime: '2026-08-31T23:30:00Z',
    estimatedCost: 18000,
    actualCost: 19800,
    status: 'confirmed',
    participantIds: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'e1',
    tripId: 'trip-goa-2026',
    bookingId: 'b1',
    title: 'Vagator Heritage Villa Deposit & 5-Night Stay',
    totalAmount: 68000,
    currency: 'INR',
    splitMethod: 'room_tier',
    paidById: 'p1',
    category: 'lodging',
    subsidyAmount: 0,
    createdAt: '2026-08-28T16:30:00Z',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    receiptName: 'Taj_Villa_Vagator_TaxInvoice.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 15280 },
      { participantId: 'p2', amountOwed: 10920 },
      { participantId: 'p3', amountOwed: 10920 },
      { participantId: 'p4', amountOwed: 8730 },
      { participantId: 'p5', amountOwed: 6870 },
      { participantId: 'p6', amountOwed: 15280 },
    ],
  },
  {
    id: 'e2',
    tripId: 'trip-goa-2026',
    bookingId: 'b2',
    title: 'Self-Drive 7-Seater SUV Rental & Insurance',
    totalAmount: 21500,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p6',
    category: 'transport',
    subsidyAmount: 0,
    createdAt: '2026-08-29T09:15:00Z',
    receiptUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
    receiptName: 'GoaWheels_Invoice_21500.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 3583.33 },
      { participantId: 'p2', amountOwed: 3583.33 },
      { participantId: 'p3', amountOwed: 3583.33 },
      { participantId: 'p4', amountOwed: 3583.33 },
      { participantId: 'p5', amountOwed: 3583.33 },
      { participantId: 'p6', amountOwed: 3583.35 },
    ],
  },
  {
    id: 'e3',
    tripId: 'trip-goa-2026',
    title: 'Airport Express Cabs & Intercity Highway Tolls',
    totalAmount: 4200,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p3',
    category: 'transport',
    subsidyAmount: 0,
    createdAt: '2026-08-28T14:00:00Z',
    receiptName: 'GoaCabs_FastagReceipts.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 700.00 },
      { participantId: 'p2', amountOwed: 700.00 },
      { participantId: 'p3', amountOwed: 700.00 },
      { participantId: 'p4', amountOwed: 700.00 },
      { participantId: 'p5', amountOwed: 700.00 },
      { participantId: 'p6', amountOwed: 700.00 },
    ],
  },
  {
    id: 'e4',
    tripId: 'trip-goa-2026',
    bookingId: 'b3',
    title: 'Mandovi Sunset Catamaran & Scuba Gear Rental',
    totalAmount: 30000,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p1',
    category: 'activity',
    subsidyAmount: 0,
    createdAt: '2026-08-30T17:45:00Z',
    receiptUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    receiptName: 'MandoviMarine_Catamaran_Charter.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 7500.00 },
      { participantId: 'p2', amountOwed: 7500.00 },
      { participantId: 'p3', amountOwed: 7500.00 },
      { participantId: 'p6', amountOwed: 7500.00 },
    ],
  },
  {
    id: 'e5',
    tripId: 'trip-goa-2026',
    bookingId: 'b5',
    title: 'Thalassa Seafood Dinner & Greek Wine Pairing',
    totalAmount: 19800,
    currency: 'INR',
    splitMethod: 'organizer_subsidy',
    paidById: 'p3',
    category: 'food',
    subsidyAmount: 4800,
    createdAt: '2026-08-31T23:15:00Z',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=80',
    receiptName: 'Thalassa_Dinner_Bill_19800.png',
    allocations: [
      { participantId: 'p1', amountOwed: 2500.00 },
      { participantId: 'p2', amountOwed: 2500.00 },
      { participantId: 'p3', amountOwed: 2500.00 },
      { participantId: 'p4', amountOwed: 2500.00 },
      { participantId: 'p5', amountOwed: 2500.00 },
      { participantId: 'p6', amountOwed: 2500.00 },
    ],
  },
  {
    id: 'e6',
    tripId: 'trip-goa-2026',
    title: "Fisherman's Wharf Goan Prawn Curry & Thali Lunch",
    totalAmount: 7200,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p4',
    category: 'food',
    subsidyAmount: 0,
    createdAt: '2026-09-01T13:45:00Z',
    receiptName: 'FishermansWharf_Lunch_TaxInvoice.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 1200.00 },
      { participantId: 'p2', amountOwed: 1200.00 },
      { participantId: 'p3', amountOwed: 1200.00 },
      { participantId: 'p4', amountOwed: 1200.00 },
      { participantId: 'p5', amountOwed: 1200.00 },
      { participantId: 'p6', amountOwed: 1200.00 },
    ],
  },
  {
    id: 'e7',
    tripId: 'trip-goa-2026',
    title: 'Curlies Beach Shack Live Music & Sundowner Drinks',
    totalAmount: 9600,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p5',
    category: 'activity',
    subsidyAmount: 0,
    createdAt: '2026-09-01T23:30:00Z',
    receiptName: 'Curlies_Anjuna_Receipt.jpg',
    allocations: [
      { participantId: 'p1', amountOwed: 1600.00 },
      { participantId: 'p2', amountOwed: 1600.00 },
      { participantId: 'p3', amountOwed: 1600.00 },
      { participantId: 'p4', amountOwed: 1600.00 },
      { participantId: 'p5', amountOwed: 1600.00 },
      { participantId: 'p6', amountOwed: 1600.00 },
    ],
  },
  {
    id: 'e8',
    tripId: 'trip-goa-2026',
    bookingId: 'b4',
    title: 'Gokarna Trail Passes & Certified Local Guide Fee',
    totalAmount: 8500,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p2',
    category: 'activity',
    subsidyAmount: 0,
    createdAt: '2026-09-03T14:30:00Z',
    receiptName: 'WesternGhats_TrekGuide_Receipt.pdf',
    allocations: [
      { participantId: 'p2', amountOwed: 2125.00 },
      { participantId: 'p3', amountOwed: 2125.00 },
      { participantId: 'p4', amountOwed: 2125.00 },
      { participantId: 'p5', amountOwed: 2125.00 },
    ],
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay1',
    tripId: 'trip-goa-2026',
    payerId: 'p4',
    payeeId: 'p1',
    amount: 5000,
    note: 'UPI advance payment via Google Pay (Ref: UPI/6329018283)',
    createdAt: '2026-09-04T11:00:00Z',
  },
];

export const INITIAL_EVENTS: LedgerEvent[] = [
  {
    id: 'evt-1',
    tripId: 'trip-goa-2026',
    eventType: 'TRIP_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-08-20T09:00:00Z',
    description: 'Trip "Goa & Gokarna Sunsets 2026" initialized with invite code GOA2026 and budget cap ₹2,50,000.',
    payload: { title: 'Goa & Gokarna Sunsets 2026', destination: 'Goa & Gokarna, India', inviteCode: 'GOA2026', budgetCeiling: 250000 },
    sequenceNum: 1,
  },
  {
    id: 'evt-2',
    tripId: 'trip-goa-2026',
    eventType: 'PARTICIPANT_ADDED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-08-22T14:30:00Z',
    description: 'Added 5 squad travelers (Ananya, Rohan, Priya, Diya, Kabir) with verified UPI payment handles.',
    payload: { count: 5, roster: ['Ananya Iyer', 'Rohan Mehta', 'Priya Patel', 'Diya Verma', 'Kabir Roy'] },
    sequenceNum: 2,
  },
  {
    id: 'evt-3',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-08-24T11:00:00Z',
    description: 'Confirmed reservation for Heritage Beach Villa (Vagator) with Taj Host Villas Goa (₹68,000.00).',
    payload: { bookingId: 'b1', title: 'Heritage Beach Villa & Private Pool (Vagator)', vendor: 'Taj Host Villas Goa', amount: 68000, category: 'lodging' },
    sequenceNum: 3,
  },
  {
    id: 'evt-4',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-08-25T15:20:00Z',
    description: 'Confirmed 7-seater SUV rental booking with Goa Wheels Self-Drive (₹21,500.00).',
    payload: { bookingId: 'b2', title: 'Self-Drive 7-Seater SUV Rentals & Airport Pickup', vendor: 'Goa Wheels Self-Drive', amount: 21500, category: 'transport' },
    sequenceNum: 4,
  },
  {
    id: 'evt-5',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p3',
    actorName: 'Rohan Mehta',
    timestamp: '2026-08-28T14:00:00Z',
    description: 'Rohan Mehta paid ₹4,200.00 for Airport Express Cabs & Tolls, split equally across all 6 members (₹700.00 each).',
    payload: { expenseId: 'e3', amount: 4200, splitMethod: 'equal' },
    sequenceNum: 5,
  },
  {
    id: 'evt-6',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-08-28T16:30:00Z',
    description: 'Srushti Sharma paid ₹68,000.00 for Vagator Heritage Villa stay using weighted Room-Tier split with verified tax invoice.',
    payload: { expenseId: 'e1', amount: 68000, splitMethod: 'room_tier' },
    sequenceNum: 6,
  },
  {
    id: 'evt-7',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p6',
    actorName: 'Kabir Roy',
    timestamp: '2026-08-29T09:15:00Z',
    description: 'Kabir Roy paid ₹21,500.00 for 7-seater SUV rental, split equally across all 6 members (₹3,583.33 each).',
    payload: { expenseId: 'e2', amount: 21500, splitMethod: 'equal' },
    sequenceNum: 7,
  },
  {
    id: 'evt-8',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-08-30T10:00:00Z',
    description: 'Confirmed booking for Private Sunset Catamaran Yacht Charter with Mandovi Luxury Marine (₹30,000.00).',
    payload: { bookingId: 'b3', vendor: 'Mandovi Luxury Marine', amount: 30000, category: 'activity' },
    sequenceNum: 8,
  },
  {
    id: 'evt-9',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-08-30T17:45:00Z',
    description: 'Srushti Sharma paid ₹30,000.00 for Sunset Catamaran Yacht & Scuba, scoped strictly among the 4 participating travelers (₹7,500.00 each).',
    payload: { expenseId: 'e4', amount: 30000, splitMethod: 'equal' },
    sequenceNum: 9,
  },
  {
    id: 'evt-10',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-08-31T14:30:00Z',
    description: 'Confirmed dinner reservation at Thalassa Beach Restaurant (₹19,800.00).',
    payload: { bookingId: 'b5', vendor: 'Thalassa Beach Restaurant', amount: 19800, category: 'food' },
    sequenceNum: 10,
  },
  {
    id: 'evt-11',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p3',
    actorName: 'Rohan Mehta',
    timestamp: '2026-08-31T23:15:00Z',
    description: 'Rohan Mehta paid ₹19,800.00 at Thalassa; Srushti Sharma subsidized ₹4,800.00 for luxury wines, leaving ₹15,000 net split across all 6 members (₹2,500.00 each).',
    payload: { expenseId: 'e5', amount: 19800, subsidy: 4800, splitMethod: 'organizer_subsidy' },
    sequenceNum: 11,
  },
  {
    id: 'evt-12',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p4',
    actorName: 'Priya Patel',
    timestamp: '2026-09-01T13:45:00Z',
    description: "Priya Patel paid ₹7,200.00 at Fisherman's Wharf, split equally among all 6 members (₹1,200.00 each).",
    payload: { expenseId: 'e6', amount: 7200, splitMethod: 'equal' },
    sequenceNum: 12,
  },
  {
    id: 'evt-13',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p5',
    actorName: 'Diya Verma',
    timestamp: '2026-09-01T23:30:00Z',
    description: 'Diya Verma paid ₹9,600.00 at Curlies Beach Shack, split equally among all 6 members (₹1,600.00 each).',
    payload: { expenseId: 'e7', amount: 9600, splitMethod: 'equal' },
    sequenceNum: 13,
  },
  {
    id: 'evt-14',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p2',
    actorName: 'Ananya Iyer',
    timestamp: '2026-09-02T16:00:00Z',
    description: 'Confirmed reservation for Gokarna Coastal Cliff Trek with Western Ghats Treks (₹8,500.00).',
    payload: { bookingId: 'b4', vendor: 'Western Ghats Treks', amount: 8500, category: 'activity' },
    sequenceNum: 14,
  },
  {
    id: 'evt-15',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p2',
    actorName: 'Ananya Iyer',
    timestamp: '2026-09-03T14:30:00Z',
    description: 'Ananya Iyer paid ₹8,500.00 for Gokarna Trail Passes & Guide Fee, divided strictly among the 4 participating hikers (₹2,125.00 each).',
    payload: { expenseId: 'e8', amount: 8500, splitMethod: 'equal' },
    sequenceNum: 15,
  },
  {
    id: 'evt-16',
    tripId: 'trip-goa-2026',
    eventType: 'PAYMENT_RECORDED',
    actorId: 'p4',
    actorName: 'Priya Patel',
    timestamp: '2026-09-04T11:00:00Z',
    description: 'Recorded direct UPI settlement payment of ₹5,000.00 from Priya Patel to Srushti Sharma (Ref: UPI/6329018283).',
    payload: { paymentId: 'pay1', amount: 5000, payer: 'Priya Patel', payee: 'Srushti Sharma' },
    sequenceNum: 16,
  },
];
