import { NextResponse } from 'next/server';

const GROQ_API_KEY =
  process.env.GROQ_API_KEY || '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';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { valueType, referenceId, headlineValue, contextData, tripTitle } = body;

    const prompt = `You are a transparent, friendly financial AI auditor for an Indian group travel app called Tulis.
A user asked to explain a ledger figure:
Type: ${valueType || 'general'}
Reference / ID: ${referenceId || 'N/A'}
Headline Value: ${headlineValue || 'N/A'}
Trip: ${tripTitle || 'Trip'}
Context / Details:
${JSON.stringify(contextData || {})}

Provide a concise, 2-3 sentence, crystal-clear explanation of why this specific number is what it is, reassuring the traveler that it has been strictly zero-sum reconciled. Keep it friendly, empathetic, authentic, and free of unnecessary corporate jargon.`;

    try {
      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${GROQ_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: 'openai/gpt-oss-20b',
          messages: [{ role: 'user', content: prompt }],
          temperature: 0.3,
          max_tokens: 250,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        const explanation = data.choices?.[0]?.message?.content || '';
        if (explanation) {
          return NextResponse.json({
            success: true,
            explanation,
            model: 'AI Neural Engine',
          });
        }
      }
    } catch (apiErr) {
      console.warn('Groq explain endpoint fallback:', apiErr);
    }

    // Default intelligent fallbacks by valueType
    let fallbackText = `This value was computed deterministically by the Tulis ledger engine and has zero residual drift.`;
    if (valueType === 'settlement') {
      fallbackText = `This settlement payment was generated by greedy bipartite debt simplification to clear all group liabilities in a single transfer.`;
    } else if (valueType === 'variance') {
      fallbackText = `This variance represents the real-time difference between planned booking costs and actual receipts recorded on the trip.`;
    } else if (valueType === 'anomaly') {
      fallbackText = `This anomaly was flagged algorithmically because two overlapping commitments or outlier rates were detected.`;
    } else if (valueType === 'balance') {
      fallbackText = `This balance summarizes your net position: all upfront payments minus your consumed activity shares.`;
    }

    return NextResponse.json({
      success: true,
      explanation: fallbackText,
      fallback: true,
    });
  } catch (err: any) {
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}
